from typing import Protocol, List, Optional
import uuid
from app.domain.models.session import Session

class ISessionRepository(Protocol):
    def create(self, s: Session) -> Session: ...
    def get_by_jti(self, jti: str) -> Optional[Session]: ...
    def revoke(self, jti: str) -> None: ...
    def revoke_all_for_user(self, user_id: uuid.UUID) -> int: ...
    def list_active_for_user(self, user_id: uuid.UUID) -> List[Session]: ...
