from typing import Protocol, Optional
from app.domain.models.token import OneTimeToken, TokenType

class ITokenRepository(Protocol):
    def create(self, t: OneTimeToken) -> OneTimeToken: ...
    def get_valid(self, token: str, token_type: TokenType) -> Optional[OneTimeToken]: ...
    def mark_used(self, t: OneTimeToken) -> None: ...
