from typing import Protocol, Optional, List
import uuid
from app.domain.models.user import User

class IUserRepository(Protocol):
    def create(self, user: User) -> User: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_id(self, user_id: uuid.UUID) -> Optional[User]: ...
    def update(self, user: User) -> User: ...
